<?php
ct()->header();
?>
<?php
ct()->template('home-page/parts/hero-section.php');
ct()->template('home-page/parts/services.php');
ct()->template('home-page/parts/personal.php');
ct()->template('home-page/parts/about.php');
ct()->template('home-page/parts/reviews.php');
ct()->template('home-page/parts/form-section.php');
?>
<?php
ct()->footer();
?>
